[2024-04-21T11:09:07.628+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-21T11:09:07.642+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-21T11:09:07.643+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T11:09:07.665+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_rub> on 2024-04-02 00:00:00+00:00
[2024-04-21T11:09:07.671+0000] {standard_task_runner.py:60} INFO - Started process 2858 to run task
[2024-04-21T11:09:07.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_rub', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '2123', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpal0xgxl1']
[2024-04-21T11:09:07.680+0000] {standard_task_runner.py:88} INFO - Job 2123: Subtask get_data_rub
[2024-04-21T11:09:07.746+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T11:09:07.811+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T11:09:07.866+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_rub' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-21T11:09:18.333+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 37, in get_data_rub
    currencies_date = datetime.strptime(currency_data['Date'][:10], '%Y-%m-%d')
KeyError: 'Date'
[2024-04-21T11:09:18.354+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=get_data_rub, execution_date=20240402T000000, start_date=20240421T110907, end_date=20240421T110918
[2024-04-21T11:09:18.389+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2123 for task get_data_rub ('Date'; 2858)
[2024-04-21T11:09:18.429+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T11:09:18.456+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T12:23:42.139+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-27T12:23:42.170+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-27T12:23:42.175+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-27T12:23:42.242+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_rub> on 2024-04-02 00:00:00+00:00
[2024-04-27T12:23:42.255+0000] {standard_task_runner.py:60} INFO - Started process 2143 to run task
[2024-04-27T12:23:42.285+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_rub', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '2406', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpcn_1l5f_']
[2024-04-27T12:23:42.292+0000] {standard_task_runner.py:88} INFO - Job 2406: Subtask get_data_rub
[2024-04-27T12:23:42.542+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_rub scheduled__2024-04-02T00:00:00+00:00 [running]> on host 65a8688265d1
[2024-04-27T12:23:42.719+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-27T12:23:42.916+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_rub' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-27T12:23:56.416+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 39, in get_data_rub
    currencies_date = datetime.strptime(currency_data['Date'][:10], '%Y-%m-%d')
KeyError: 'Date'
[2024-04-27T12:23:56.804+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=get_data_rub, execution_date=20240402T000000, start_date=20240427T122342, end_date=20240427T122356
[2024-04-27T12:23:57.657+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2406 for task get_data_rub ('Date'; 2143)
[2024-04-27T12:23:57.932+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-27T12:23:58.079+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-27T12:23:58.802+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
