[2024-05-03T12:45:37.839+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:45:37.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:45:38.032+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:37.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:45:38.262+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:38.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:45:38.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:45:38.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.844 seconds
[2024-05-03T12:46:14.823+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:14.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:46:14.864+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:14.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:15.771+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:15.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:46:15.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:16.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 1.978 seconds
[2024-05-03T12:46:46.996+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:46.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:46:47.001+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:47.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:47.044+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:47.037+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:46:47.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:46:47.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.093 seconds
[2024-05-03T12:47:17.428+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:17.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:47:17.433+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:17.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:17.472+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:17.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:47:17.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:17.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.082 seconds
[2024-05-03T12:47:47.752+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:47.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:47:47.758+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:47.757+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:47.795+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:47.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:47:47.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:47:47.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.080 seconds
[2024-05-03T12:48:18.184+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:18.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:48:18.560+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:18.559+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:18.842+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:18.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:48:18.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:18.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.784 seconds
[2024-05-03T12:48:49.644+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:49.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:48:49.648+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:49.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:49.681+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:49.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:48:49.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:48:49.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.069 seconds
[2024-05-03T12:49:19.808+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:19.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:49:19.819+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:19.818+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:19.879+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:19.870+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:49:19.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:19.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.112 seconds
[2024-05-03T12:49:50.115+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:50.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:49:50.120+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:50.120+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:50.169+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:50.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:49:50.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:49:50.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.111 seconds
[2024-05-03T12:50:20.353+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:20.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:50:20.358+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:20.357+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:20.393+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:20.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:50:20.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:20.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.080 seconds
[2024-05-03T12:50:50.676+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:50.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:50:50.680+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:50.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:50.717+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:50.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:50:50.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:50:50.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.080 seconds
[2024-05-03T12:51:21.055+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:21.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:51:21.068+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:21.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:21.117+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:21.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:51:21.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:21.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.145 seconds
[2024-05-03T12:51:51.305+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:51.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:51:51.331+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:51.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:51.498+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:51.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:51:51.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:51:51.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.285 seconds
[2024-05-03T12:52:22.378+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:22.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:52:22.396+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:22.394+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:23.586+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:23.573+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:52:23.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:25.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 2.690 seconds
[2024-05-03T12:52:55.754+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:55.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:52:55.774+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:55.773+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:56.027+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:56.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:52:56.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:52:57.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 2.170 seconds
[2024-05-03T12:53:28.871+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:53:28.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:53:28.949+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:28.948+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:53:29.093+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:29.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:53:29.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:53:29.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.365 seconds
[2024-05-03T12:53:59.891+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:53:59.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:53:59.899+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:59.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:54:00.172+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:00.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:54:00.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:54:00.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.412 seconds
[2024-05-03T12:54:31.297+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:54:31.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:54:31.317+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:31.316+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:54:31.561+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:31.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:54:31.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:54:31.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.622 seconds
[2024-05-03T12:55:04.011+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:55:04.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:55:04.120+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:04.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:55:06.620+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:05.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:55:06.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:55:06.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 3.072 seconds
[2024-05-03T12:55:59.219+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:55:59.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:55:59.469+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:59.362+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:56:01.189+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:00.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:56:01.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:56:02.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 4.028 seconds
[2024-05-03T12:56:37.608+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:56:37.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:56:37.674+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:37.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:56:39.440+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:39.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:56:39.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:56:40.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 2.515 seconds
[2024-05-03T12:57:15.923+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:16.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:57:16.092+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:16.092+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:21.796+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:21.256+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:57:22.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:23.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 7.910 seconds
[2024-05-03T12:57:54.107+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:54.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:57:54.160+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:54.131+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:54.413+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:54.383+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:57:54.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:57:56.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 2.392 seconds
[2024-05-03T12:58:27.891+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:58:27.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-03T12:58:28.200+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:28.198+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:58:29.237+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:29.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-03T12:58:29.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-03T12:58:29.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 2.253 seconds
