[2024-04-20T13:44:02.915+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing_usd.get_data scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T13:44:02.937+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing_usd.get_data scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T13:44:02.938+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-20T13:44:02.980+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-19 00:00:00+00:00
[2024-04-20T13:44:02.997+0000] {standard_task_runner.py:60} INFO - Started process 808 to run task
[2024-04-20T13:44:03.013+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing_usd', 'get_data', 'scheduled__2024-04-19T00:00:00+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_usd.py', '--cfg-path', '/tmp/tmpqy24x6w4']
[2024-04-20T13:44:03.017+0000] {standard_task_runner.py:88} INFO - Job 856: Subtask get_data
[2024-04-20T13:44:03.143+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing_usd.get_data scheduled__2024-04-19T00:00:00+00:00 [running]> on host 31aa6d9ea6ff
[2024-04-20T13:44:03.224+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-20T13:44:03.294+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing_usd' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-19T00:00:00+00:00'
[2024-04-20T13:44:04.044+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_usd.py", line 12, in get_data
    historical_data = data['data'][f'{year}-{month}-{day}']
KeyError: '2024-4-19'
[2024-04-20T13:44:04.107+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing_usd, task_id=get_data, execution_date=20240419T000000, start_date=20240420T134402, end_date=20240420T134404
[2024-04-20T13:44:04.141+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 856 for task get_data ('2024-4-19'; 808)
[2024-04-20T13:44:04.171+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T13:44:04.227+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
