[2024-05-02T07:58:03.847+0000] {processor.py:161} INFO - Started process (PID=940) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:03.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T07:58:03.854+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:58:03.853+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:03.906+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:58:03.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T07:58:03.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:03.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.131 seconds
[2024-05-02T07:58:34.948+0000] {processor.py:161} INFO - Started process (PID=951) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:34.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T07:58:34.953+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:58:34.952+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:34.990+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:58:34.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T07:58:34.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:58:35.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.109 seconds
[2024-05-02T07:59:05.459+0000] {processor.py:161} INFO - Started process (PID=962) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:05.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T07:59:05.463+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:59:05.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:05.529+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:59:05.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T07:59:05.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:05.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.199 seconds
[2024-05-02T07:59:35.908+0000] {processor.py:161} INFO - Started process (PID=973) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:35.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T07:59:35.911+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:59:35.911+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:35.950+0000] {logging_mixin.py:188} INFO - [2024-05-02T07:59:35.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T07:59:35.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T07:59:35.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.076 seconds
[2024-05-02T08:00:06.302+0000] {processor.py:161} INFO - Started process (PID=984) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:06.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:00:06.306+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:00:06.306+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:06.344+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:00:06.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:00:06.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:06.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.079 seconds
[2024-05-02T08:00:37.332+0000] {processor.py:161} INFO - Started process (PID=994) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:37.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:00:37.336+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:00:37.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:37.383+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:00:37.375+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:00:37.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:00:37.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.107 seconds
[2024-05-02T08:01:08.400+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:08.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:01:08.405+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:01:08.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:08.456+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:01:08.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:01:08.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:08.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.119 seconds
[2024-05-02T08:01:39.045+0000] {processor.py:161} INFO - Started process (PID=1016) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:39.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:01:39.049+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:01:39.048+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:39.092+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:01:39.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:01:39.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:01:39.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.086 seconds
[2024-05-02T08:02:09.694+0000] {processor.py:161} INFO - Started process (PID=1027) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:09.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:02:09.710+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:02:09.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:09.815+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:02:09.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:02:09.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:09.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.245 seconds
[2024-05-02T08:02:40.042+0000] {processor.py:161} INFO - Started process (PID=1038) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:40.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:02:40.046+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:02:40.046+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:40.095+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:02:40.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:02:40.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:02:40.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.103 seconds
[2024-05-02T08:03:10.565+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:10.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:03:10.571+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:03:10.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:10.651+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:03:10.644+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:03:10.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:10.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.168 seconds
[2024-05-02T08:03:41.599+0000] {processor.py:161} INFO - Started process (PID=1060) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:41.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:03:41.606+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:03:41.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:41.671+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:03:41.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:03:41.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:03:41.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.128 seconds
[2024-05-02T08:04:12.025+0000] {processor.py:161} INFO - Started process (PID=1072) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:12.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:04:12.029+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:04:12.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:12.067+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:04:12.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:04:12.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:12.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.087 seconds
[2024-05-02T08:04:42.317+0000] {processor.py:161} INFO - Started process (PID=1083) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:42.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:04:42.321+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:04:42.320+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:42.356+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:04:42.350+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:04:42.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:04:42.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.075 seconds
[2024-05-02T08:05:12.630+0000] {processor.py:161} INFO - Started process (PID=1093) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:12.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:05:12.634+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:05:12.634+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:12.675+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:05:12.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:05:12.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:12.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.085 seconds
[2024-05-02T08:05:43.092+0000] {processor.py:161} INFO - Started process (PID=1104) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:43.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:05:43.096+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:05:43.096+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:43.161+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:05:43.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:05:43.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:05:43.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.131 seconds
[2024-05-02T08:06:13.575+0000] {processor.py:161} INFO - Started process (PID=1115) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:13.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:06:13.579+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:06:13.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:13.625+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:06:13.617+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:06:13.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:13.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.087 seconds
[2024-05-02T08:06:44.023+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:44.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:06:44.026+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:06:44.026+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:44.062+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:06:44.054+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:06:44.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:06:44.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.077 seconds
[2024-05-02T08:07:14.534+0000] {processor.py:161} INFO - Started process (PID=1137) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:14.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:07:14.537+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:07:14.537+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:14.574+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:07:14.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:07:14.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:14.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.081 seconds
[2024-05-02T08:07:44.729+0000] {processor.py:161} INFO - Started process (PID=1148) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:44.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:07:44.733+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:07:44.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:44.773+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:07:44.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:07:44.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:07:44.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.082 seconds
[2024-05-02T08:08:14.958+0000] {processor.py:161} INFO - Started process (PID=1159) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:14.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:08:14.962+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:08:14.961+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:15.002+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:08:14.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:08:15.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:15.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.083 seconds
[2024-05-02T08:08:45.184+0000] {processor.py:161} INFO - Started process (PID=1170) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:45.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:08:45.188+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:08:45.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:45.234+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:08:45.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:08:45.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:08:45.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.106 seconds
[2024-05-02T08:09:15.513+0000] {processor.py:161} INFO - Started process (PID=1181) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:15.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:09:15.518+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:09:15.517+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:15.571+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:09:15.565+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:09:15.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:15.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.105 seconds
[2024-05-02T08:09:46.051+0000] {processor.py:161} INFO - Started process (PID=1192) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:46.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:09:46.054+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:09:46.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:46.089+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:09:46.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:09:46.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:09:46.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.076 seconds
[2024-05-02T08:10:16.705+0000] {processor.py:161} INFO - Started process (PID=1203) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:16.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:10:16.718+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:10:16.718+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:16.752+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:10:16.746+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:10:16.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:16.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.085 seconds
[2024-05-02T08:10:47.339+0000] {processor.py:161} INFO - Started process (PID=1214) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:47.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:10:47.347+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:10:47.346+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:47.464+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:10:47.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:10:47.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:10:47.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.438 seconds
[2024-05-02T08:11:18.109+0000] {processor.py:161} INFO - Started process (PID=1225) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:18.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:11:18.112+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:11:18.112+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:18.146+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:11:18.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:11:18.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:18.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T08:11:48.320+0000] {processor.py:161} INFO - Started process (PID=1236) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:48.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:11:48.324+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:11:48.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:48.362+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:11:48.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:11:48.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:11:48.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.077 seconds
[2024-05-02T08:12:18.655+0000] {processor.py:161} INFO - Started process (PID=1247) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:18.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:12:18.658+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:12:18.658+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:18.695+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:12:18.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:12:18.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:18.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T08:12:49.212+0000] {processor.py:161} INFO - Started process (PID=1259) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:49.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:12:49.215+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:12:49.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:49.251+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:12:49.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:12:49.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:12:49.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.074 seconds
[2024-05-02T08:13:19.578+0000] {processor.py:161} INFO - Started process (PID=1270) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:19.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:13:19.582+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:13:19.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:19.619+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:13:19.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:13:19.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:19.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.074 seconds
[2024-05-02T08:13:49.941+0000] {processor.py:161} INFO - Started process (PID=1281) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:49.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:13:49.945+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:13:49.945+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:49.997+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:13:49.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:13:50.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:13:50.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.104 seconds
[2024-05-02T08:14:20.502+0000] {processor.py:161} INFO - Started process (PID=1292) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:20.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:14:20.505+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:14:20.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:20.548+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:14:20.541+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:14:20.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:20.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.085 seconds
[2024-05-02T08:14:50.907+0000] {processor.py:161} INFO - Started process (PID=1303) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:50.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:14:50.911+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:14:50.910+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:50.943+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:14:50.938+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:14:50.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:14:50.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.070 seconds
[2024-05-02T08:15:21.070+0000] {processor.py:161} INFO - Started process (PID=1315) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:21.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:15:21.074+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:15:21.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:21.124+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:15:21.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:15:21.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:21.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.100 seconds
[2024-05-02T08:15:51.486+0000] {processor.py:161} INFO - Started process (PID=1326) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:51.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:15:51.490+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:15:51.490+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:51.537+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:15:51.530+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:15:51.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:15:51.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.093 seconds
[2024-05-02T08:16:21.708+0000] {processor.py:161} INFO - Started process (PID=1337) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:21.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:16:21.711+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:16:21.711+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:21.753+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:16:21.746+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:16:21.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:21.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.087 seconds
[2024-05-02T08:16:52.179+0000] {processor.py:161} INFO - Started process (PID=1348) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:52.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:16:52.183+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:16:52.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:52.226+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:16:52.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:16:52.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:16:52.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.087 seconds
[2024-05-02T08:17:22.452+0000] {processor.py:161} INFO - Started process (PID=1359) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:22.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:17:22.456+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:17:22.455+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:22.493+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:17:22.487+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:17:22.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:22.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.079 seconds
[2024-05-02T08:17:52.698+0000] {processor.py:161} INFO - Started process (PID=1370) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:52.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:17:52.702+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:17:52.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:52.746+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:17:52.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:17:52.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:17:52.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.081 seconds
[2024-05-02T08:18:23.374+0000] {processor.py:161} INFO - Started process (PID=1381) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:23.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:18:23.379+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:18:23.379+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:23.421+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:18:23.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:18:23.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:23.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.094 seconds
[2024-05-02T08:18:54.129+0000] {processor.py:161} INFO - Started process (PID=1392) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:54.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:18:54.134+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:18:54.133+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:54.196+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:18:54.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:18:54.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:18:54.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.126 seconds
[2024-05-02T08:19:24.669+0000] {processor.py:161} INFO - Started process (PID=1402) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:24.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:19:24.673+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:19:24.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:24.707+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:19:24.701+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:19:24.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:24.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.072 seconds
[2024-05-02T08:19:54.832+0000] {processor.py:161} INFO - Started process (PID=1413) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:54.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:19:54.835+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:19:54.835+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:54.873+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:19:54.866+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:19:54.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:19:54.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.077 seconds
[2024-05-02T08:20:25.168+0000] {processor.py:161} INFO - Started process (PID=1424) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:25.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:20:25.172+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:20:25.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:25.213+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:20:25.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:20:25.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:25.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.091 seconds
[2024-05-02T08:20:55.395+0000] {processor.py:161} INFO - Started process (PID=1435) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:55.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:20:55.399+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:20:55.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:55.465+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:20:55.452+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:20:55.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:20:55.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.130 seconds
[2024-05-02T08:21:25.836+0000] {processor.py:161} INFO - Started process (PID=1445) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:25.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:21:25.840+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:21:25.839+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:25.899+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:21:25.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:21:25.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:25.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.106 seconds
[2024-05-02T08:21:56.572+0000] {processor.py:161} INFO - Started process (PID=1462) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:56.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:21:56.580+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:21:56.579+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:56.621+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:21:56.614+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:21:56.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:21:56.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.127 seconds
[2024-05-02T08:22:27.599+0000] {processor.py:161} INFO - Started process (PID=1482) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:27.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:22:27.604+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:22:27.604+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:27.660+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:22:27.651+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:22:27.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:27.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.119 seconds
[2024-05-02T08:22:57.987+0000] {processor.py:161} INFO - Started process (PID=1493) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:57.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:22:57.991+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:22:57.990+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:58.030+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:22:58.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:22:58.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:22:58.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T08:23:28.473+0000] {processor.py:161} INFO - Started process (PID=1504) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:28.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:23:28.478+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:23:28.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:28.528+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:23:28.522+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:23:28.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:28.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.106 seconds
[2024-05-02T08:23:58.889+0000] {processor.py:161} INFO - Started process (PID=1515) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:58.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:23:58.893+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:23:58.892+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:58.931+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:23:58.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:23:58.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:23:58.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.080 seconds
[2024-05-02T08:24:29.537+0000] {processor.py:161} INFO - Started process (PID=1526) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:24:29.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:24:29.547+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:24:29.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:24:29.597+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:24:29.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:24:29.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:24:29.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.110 seconds
[2024-05-02T08:25:00.370+0000] {processor.py:161} INFO - Started process (PID=1536) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:00.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:25:00.373+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:25:00.373+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:00.427+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:25:00.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:25:00.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:00.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.097 seconds
[2024-05-02T08:25:30.566+0000] {processor.py:161} INFO - Started process (PID=1547) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:30.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:25:30.570+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:25:30.569+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:30.621+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:25:30.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:25:30.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:25:30.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.112 seconds
[2024-05-02T08:26:00.860+0000] {processor.py:161} INFO - Started process (PID=1557) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:00.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:26:00.867+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:26:00.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:00.920+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:26:00.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:26:00.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:00.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.119 seconds
[2024-05-02T08:26:31.389+0000] {processor.py:161} INFO - Started process (PID=1568) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:31.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:26:31.393+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:26:31.392+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:31.435+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:26:31.428+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:26:31.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:26:31.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.175 seconds
[2024-05-02T08:27:02.193+0000] {processor.py:161} INFO - Started process (PID=1579) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:02.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:27:02.197+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:27:02.197+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:02.244+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:27:02.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:27:02.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:02.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.095 seconds
[2024-05-02T08:27:33.050+0000] {processor.py:161} INFO - Started process (PID=1590) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:33.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:27:33.055+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:27:33.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:33.095+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:27:33.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:27:33.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:27:33.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.088 seconds
[2024-05-02T08:28:05.153+0000] {processor.py:161} INFO - Started process (PID=1601) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:05.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:28:05.157+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:28:05.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:05.194+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:28:05.188+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:28:05.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:05.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T08:28:35.335+0000] {processor.py:161} INFO - Started process (PID=1612) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:35.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:28:35.338+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:28:35.338+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:35.381+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:28:35.375+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:28:35.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:28:35.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.082 seconds
[2024-05-02T08:29:05.621+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:05.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:29:05.625+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:29:05.624+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:05.663+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:29:05.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:29:05.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:05.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.089 seconds
[2024-05-02T08:29:36.109+0000] {processor.py:161} INFO - Started process (PID=1635) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:36.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:29:36.114+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:29:36.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:36.157+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:29:36.149+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:29:36.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:29:36.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.083 seconds
[2024-05-02T08:30:06.347+0000] {processor.py:161} INFO - Started process (PID=1646) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:06.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:30:06.351+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:30:06.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:06.384+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:30:06.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:30:06.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:06.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.071 seconds
[2024-05-02T08:30:36.685+0000] {processor.py:161} INFO - Started process (PID=1656) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:36.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:30:36.692+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:30:36.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:36.727+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:30:36.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:30:36.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:30:36.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.082 seconds
[2024-05-02T08:31:07.278+0000] {processor.py:161} INFO - Started process (PID=1667) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:07.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:31:07.284+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:31:07.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:07.418+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:31:07.392+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:31:07.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:07.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.332 seconds
[2024-05-02T08:31:37.891+0000] {processor.py:161} INFO - Started process (PID=1678) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:37.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:31:37.895+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:31:37.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:37.939+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:31:37.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:31:37.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:31:37.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.085 seconds
[2024-05-02T08:32:08.135+0000] {processor.py:161} INFO - Started process (PID=1689) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:08.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:32:08.138+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:32:08.137+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:08.173+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:32:08.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:32:08.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:08.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.079 seconds
[2024-05-02T08:32:38.337+0000] {processor.py:161} INFO - Started process (PID=1699) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:38.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:32:38.341+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:32:38.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:38.390+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:32:38.381+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:32:38.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:32:38.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.097 seconds
[2024-05-02T08:33:08.788+0000] {processor.py:161} INFO - Started process (PID=1709) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:08.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:33:08.792+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:33:08.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:08.827+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:33:08.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:33:08.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:08.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T08:33:39.765+0000] {processor.py:161} INFO - Started process (PID=1719) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:39.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:33:39.770+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:33:39.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:39.830+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:33:39.816+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:33:39.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:33:39.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.166 seconds
[2024-05-02T08:34:10.292+0000] {processor.py:161} INFO - Started process (PID=1730) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:10.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:34:10.295+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:34:10.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:10.333+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:34:10.327+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:34:10.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:10.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.080 seconds
[2024-05-02T08:34:40.455+0000] {processor.py:161} INFO - Started process (PID=1741) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:40.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:34:40.459+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:34:40.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:40.507+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:34:40.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:34:40.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:34:40.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.149 seconds
[2024-05-02T08:35:10.880+0000] {processor.py:161} INFO - Started process (PID=1752) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:10.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:35:10.885+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:35:10.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:10.948+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:35:10.939+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:35:10.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:11.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.141 seconds
[2024-05-02T08:35:41.638+0000] {processor.py:161} INFO - Started process (PID=1763) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:41.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:35:41.646+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:35:41.644+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:41.709+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:35:41.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:35:41.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:35:41.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.153 seconds
[2024-05-02T08:36:11.996+0000] {processor.py:161} INFO - Started process (PID=1774) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:36:11.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T08:36:11.999+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:36:11.999+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:36:12.037+0000] {logging_mixin.py:188} INFO - [2024-05-02T08:36:12.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T08:36:12.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T08:36:12.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.078 seconds
[2024-05-02T10:44:50.592+0000] {processor.py:161} INFO - Started process (PID=1785) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:44:50.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:44:50.612+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:44:50.606+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:44:50.724+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:44:50.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:44:50.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:44:50.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.260 seconds
[2024-05-02T10:45:21.215+0000] {processor.py:161} INFO - Started process (PID=1796) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:21.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:45:21.241+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:45:21.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:21.305+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:45:21.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:45:21.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:21.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.168 seconds
[2024-05-02T10:45:51.541+0000] {processor.py:161} INFO - Started process (PID=1808) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:51.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:45:51.545+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:45:51.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:51.589+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:45:51.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:45:51.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:45:51.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.092 seconds
[2024-05-02T10:46:22.382+0000] {processor.py:161} INFO - Started process (PID=1818) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:22.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:46:22.387+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:46:22.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:22.441+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:46:22.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:46:22.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:22.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.111 seconds
[2024-05-02T10:46:53.416+0000] {processor.py:161} INFO - Started process (PID=1828) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:53.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:46:53.421+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:46:53.420+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:53.478+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:46:53.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:46:53.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:46:53.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.120 seconds
[2024-05-02T10:47:23.781+0000] {processor.py:161} INFO - Started process (PID=1839) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:23.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:47:23.808+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:47:23.801+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:23.922+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:47:23.912+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:47:23.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:23.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.220 seconds
[2024-05-02T10:47:54.677+0000] {processor.py:161} INFO - Started process (PID=1850) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:54.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:47:54.682+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:47:54.681+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:54.756+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:47:54.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:47:54.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:47:54.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.145 seconds
[2024-05-02T10:48:24.890+0000] {processor.py:161} INFO - Started process (PID=1861) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:24.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:48:24.895+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:48:24.895+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:24.961+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:48:24.955+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:48:24.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:25.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.120 seconds
[2024-05-02T10:48:55.854+0000] {processor.py:161} INFO - Started process (PID=1872) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:55.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:48:55.858+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:48:55.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:55.903+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:48:55.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:48:55.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:48:55.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.104 seconds
[2024-05-02T10:49:26.342+0000] {processor.py:161} INFO - Started process (PID=1883) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:26.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:49:26.349+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:49:26.346+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:26.421+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:49:26.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:49:26.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:26.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.145 seconds
[2024-05-02T10:49:57.053+0000] {processor.py:161} INFO - Started process (PID=1902) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:57.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:49:57.056+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:49:57.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:57.099+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:49:57.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:49:57.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:49:57.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.086 seconds
[2024-05-02T10:50:27.933+0000] {processor.py:161} INFO - Started process (PID=1912) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:27.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:50:27.937+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:50:27.937+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:27.989+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:50:27.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:50:27.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:28.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.123 seconds
[2024-05-02T10:50:58.985+0000] {processor.py:161} INFO - Started process (PID=1923) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:58.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:50:58.990+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:50:58.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:59.062+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:50:59.054+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:50:59.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:50:59.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.136 seconds
[2024-05-02T10:51:29.310+0000] {processor.py:161} INFO - Started process (PID=1934) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:51:29.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:51:29.317+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:51:29.317+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:51:29.399+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:51:29.391+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:51:29.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:51:29.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.156 seconds
[2024-05-02T10:52:00.358+0000] {processor.py:161} INFO - Started process (PID=1944) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:00.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:52:00.364+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:52:00.363+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:00.422+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:52:00.412+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:52:00.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:00.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.134 seconds
[2024-05-02T10:52:30.630+0000] {processor.py:161} INFO - Started process (PID=1954) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:30.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:52:30.635+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:52:30.634+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:30.726+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:52:30.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:52:30.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:52:30.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.169 seconds
[2024-05-02T10:53:01.213+0000] {processor.py:161} INFO - Started process (PID=1965) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:01.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:53:01.218+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:53:01.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:01.269+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:53:01.263+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:53:01.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:01.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.116 seconds
[2024-05-02T10:53:31.617+0000] {processor.py:161} INFO - Started process (PID=1975) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:31.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:53:31.621+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:53:31.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:31.660+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:53:31.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:53:31.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:53:31.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.092 seconds
[2024-05-02T10:54:01.830+0000] {processor.py:161} INFO - Started process (PID=1986) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:54:01.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:54:01.839+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:54:01.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:54:01.884+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:54:01.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa_dag/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa_dag/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-02T10:54:01.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:54:01.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa_dag/kolesa.py took 0.101 seconds
[2024-05-02T10:54:32.322+0000] {processor.py:161} INFO - Started process (PID=1997) to work on /opt/airflow/dags/kolesa_dag/kolesa.py
[2024-05-02T10:54:32.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa_dag/kolesa.py for tasks to queue
[2024-05-02T10:54:32.331+0000] {logging_mixin.py:188} INFO - [2024-05-02T10:54:32.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa_dag/kolesa.py
