[2024-05-01T14:28:01.813+0000] {processor.py:161} INFO - Started process (PID=526) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:01.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:28:01.829+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:28:01.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:01.956+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:28:01.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:28:01.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:02.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.278 seconds
[2024-05-01T14:28:32.808+0000] {processor.py:161} INFO - Started process (PID=537) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:32.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:28:32.812+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:28:32.812+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:32.862+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:28:32.855+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:28:32.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:28:32.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.105 seconds
[2024-05-01T14:29:03.353+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:03.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:29:03.361+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:29:03.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:03.407+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:29:03.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:29:03.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:03.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.097 seconds
[2024-05-01T14:29:33.956+0000] {processor.py:161} INFO - Started process (PID=558) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:33.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:29:33.959+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:29:33.959+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:34.017+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:29:33.996+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:29:34.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:29:34.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.143 seconds
[2024-05-01T14:30:04.509+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:04.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:30:04.514+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:30:04.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:04.561+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:30:04.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:30:04.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:04.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.096 seconds
[2024-05-01T14:30:34.918+0000] {processor.py:161} INFO - Started process (PID=580) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:34.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:30:34.921+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:30:34.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:34.966+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:30:34.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:30:34.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:30:35.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.090 seconds
[2024-05-01T14:31:05.242+0000] {processor.py:161} INFO - Started process (PID=591) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:05.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:31:05.247+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:31:05.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:05.287+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:31:05.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:31:05.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:05.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.082 seconds
[2024-05-01T14:31:35.548+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:35.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:31:35.556+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:31:35.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:35.612+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:31:35.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:31:35.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:31:35.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.156 seconds
[2024-05-01T14:32:06.075+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:06.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:32:06.079+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:32:06.078+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:06.123+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:32:06.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:32:06.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:06.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.092 seconds
[2024-05-01T14:32:36.311+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:36.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:32:36.314+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:32:36.313+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:36.348+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:32:36.343+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:32:36.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:32:36.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.071 seconds
[2024-05-01T14:33:06.903+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:06.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:33:06.908+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:33:06.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:06.956+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:33:06.950+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:33:06.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:06.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.093 seconds
[2024-05-01T14:33:37.396+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:37.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:33:37.402+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:33:37.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:37.453+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:33:37.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:33:37.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:33:37.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.104 seconds
[2024-05-01T14:34:07.768+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:07.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:34:07.774+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:34:07.773+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:07.822+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:34:07.815+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:34:07.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:07.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.101 seconds
[2024-05-01T14:34:37.987+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:37.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:34:37.991+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:34:37.991+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:38.035+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:34:38.027+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:34:38.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:34:38.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.086 seconds
[2024-05-01T14:35:08.248+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:08.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:35:08.252+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:35:08.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:08.314+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:35:08.305+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:35:08.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:08.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.117 seconds
[2024-05-01T14:35:38.792+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:38.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:35:38.796+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:35:38.795+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:38.838+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:35:38.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:35:38.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:35:38.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.082 seconds
[2024-05-01T14:36:09.058+0000] {processor.py:161} INFO - Started process (PID=702) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:09.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:36:09.063+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:36:09.062+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:09.108+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:36:09.099+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:36:09.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:09.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.104 seconds
[2024-05-01T14:36:39.796+0000] {processor.py:161} INFO - Started process (PID=713) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:39.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:36:39.800+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:36:39.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:39.844+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:36:39.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:36:39.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:36:39.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.090 seconds
[2024-05-01T14:37:10.061+0000] {processor.py:161} INFO - Started process (PID=724) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:10.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:37:10.065+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:37:10.064+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:10.112+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:37:10.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:37:10.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:10.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.103 seconds
[2024-05-01T14:37:40.781+0000] {processor.py:161} INFO - Started process (PID=735) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:40.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:37:40.786+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:37:40.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:40.867+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:37:40.857+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:37:40.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:37:40.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.150 seconds
[2024-05-01T14:38:11.686+0000] {processor.py:161} INFO - Started process (PID=746) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:11.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:38:11.694+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:38:11.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:11.747+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:38:11.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:38:11.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:11.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.108 seconds
[2024-05-01T14:38:41.930+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:41.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:38:41.934+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:38:41.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:41.968+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:38:41.963+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:38:41.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:38:41.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.072 seconds
[2024-05-01T14:39:12.346+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:12.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:39:12.353+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:39:12.351+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:12.399+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:39:12.392+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:39:12.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:12.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.095 seconds
[2024-05-01T14:39:42.723+0000] {processor.py:161} INFO - Started process (PID=780) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:42.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:39:42.728+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:39:42.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:42.792+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:39:42.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:39:42.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:39:42.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.153 seconds
[2024-05-01T14:40:13.364+0000] {processor.py:161} INFO - Started process (PID=791) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:13.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:40:13.390+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:40:13.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:13.658+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:40:13.620+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:40:13.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:13.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.596 seconds
[2024-05-01T14:40:44.381+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:44.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:40:44.384+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:40:44.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:44.420+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:40:44.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:40:44.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:40:44.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.073 seconds
[2024-05-01T14:41:14.805+0000] {processor.py:161} INFO - Started process (PID=813) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:14.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:41:14.808+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:41:14.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:14.849+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:41:14.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:41:14.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:14.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.077 seconds
[2024-05-01T14:41:45.168+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:45.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:41:45.171+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:41:45.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:45.208+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:41:45.201+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:41:45.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:41:45.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.074 seconds
[2024-05-01T14:42:15.634+0000] {processor.py:161} INFO - Started process (PID=836) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:15.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:42:15.638+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:42:15.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:15.687+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:42:15.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:42:15.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:15.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.095 seconds
[2024-05-01T14:42:46.048+0000] {processor.py:161} INFO - Started process (PID=847) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:46.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:42:46.052+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:42:46.051+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:46.086+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:42:46.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:42:46.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:42:46.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.075 seconds
[2024-05-01T14:43:16.194+0000] {processor.py:161} INFO - Started process (PID=858) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:16.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:43:16.197+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:43:16.197+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:16.234+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:43:16.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:43:16.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:16.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.075 seconds
[2024-05-01T14:43:46.412+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:46.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:43:46.416+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:43:46.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:46.457+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:43:46.451+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:43:46.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:43:46.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.080 seconds
[2024-05-01T14:44:16.758+0000] {processor.py:161} INFO - Started process (PID=880) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:16.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:44:16.762+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:44:16.761+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:16.802+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:44:16.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:44:16.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:16.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.078 seconds
[2024-05-01T14:44:47.204+0000] {processor.py:161} INFO - Started process (PID=891) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:47.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:44:47.219+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:44:47.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:47.345+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:44:47.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:44:47.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:44:47.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.821 seconds
[2024-05-01T14:45:18.430+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:18.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:45:18.435+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:45:18.434+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:18.507+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:45:18.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:45:18.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:18.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.158 seconds
[2024-05-01T14:45:48.973+0000] {processor.py:161} INFO - Started process (PID=913) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:48.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:45:48.979+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:45:48.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:49.031+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:45:49.024+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:45:49.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:45:49.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.119 seconds
[2024-05-01T14:46:19.425+0000] {processor.py:161} INFO - Started process (PID=924) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:19.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:46:19.429+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:46:19.428+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:19.473+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:46:19.467+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:46:19.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:19.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.096 seconds
[2024-05-01T14:46:50.024+0000] {processor.py:161} INFO - Started process (PID=935) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:50.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:46:50.028+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:46:50.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:50.067+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:46:50.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:46:50.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:46:50.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.076 seconds
[2024-05-01T14:47:20.504+0000] {processor.py:161} INFO - Started process (PID=947) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:20.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:47:20.510+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:47:20.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:20.583+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:47:20.575+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:47:20.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:20.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.156 seconds
[2024-05-01T14:47:50.995+0000] {processor.py:161} INFO - Started process (PID=958) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:50.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:47:50.998+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:47:50.997+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:51.037+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:47:51.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:47:51.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:47:51.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.079 seconds
[2024-05-01T14:48:21.742+0000] {processor.py:161} INFO - Started process (PID=969) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:21.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:48:21.747+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:48:21.746+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:21.792+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:48:21.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:48:21.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:21.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.097 seconds
[2024-05-01T14:48:51.982+0000] {processor.py:161} INFO - Started process (PID=980) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:51.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:48:51.986+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:48:51.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:52.025+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:48:52.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:48:52.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:48:52.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.078 seconds
[2024-05-01T14:49:22.177+0000] {processor.py:161} INFO - Started process (PID=991) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:22.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:49:22.180+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:49:22.180+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:22.218+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:49:22.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:49:22.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:22.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.090 seconds
[2024-05-01T14:49:52.587+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:52.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:49:52.590+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:49:52.590+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:52.628+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:49:52.621+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:49:52.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:49:52.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.075 seconds
[2024-05-01T14:50:23.065+0000] {processor.py:161} INFO - Started process (PID=1014) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:23.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:50:23.068+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:50:23.068+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:23.101+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:50:23.095+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:50:23.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:23.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.070 seconds
[2024-05-01T14:50:53.467+0000] {processor.py:161} INFO - Started process (PID=1025) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:53.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:50:53.471+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:50:53.470+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:53.507+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:50:53.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:50:53.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:50:53.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.074 seconds
[2024-05-01T14:51:24.455+0000] {processor.py:161} INFO - Started process (PID=1042) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:24.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:51:24.459+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:51:24.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:24.503+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:51:24.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:51:24.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:24.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.086 seconds
[2024-05-01T14:51:54.940+0000] {processor.py:161} INFO - Started process (PID=1053) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:54.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:51:54.945+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:51:54.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:54.992+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:51:54.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:51:54.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:51:55.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.121 seconds
[2024-05-01T14:52:26.113+0000] {processor.py:161} INFO - Started process (PID=1064) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:26.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:52:26.120+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:52:26.119+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:26.170+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:52:26.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:52:26.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:26.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.099 seconds
[2024-05-01T14:52:56.633+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:56.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:52:56.638+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:52:56.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:56.728+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:52:56.688+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:52:56.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:52:56.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.180 seconds
[2024-05-01T14:53:27.239+0000] {processor.py:161} INFO - Started process (PID=1085) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:27.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:53:27.243+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:53:27.242+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:27.352+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:53:27.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:53:27.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:27.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.167 seconds
[2024-05-01T14:53:57.915+0000] {processor.py:161} INFO - Started process (PID=1096) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:57.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:53:57.920+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:53:57.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:58.002+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:53:57.990+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:53:58.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:53:58.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.192 seconds
[2024-05-01T14:54:28.234+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:28.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:54:28.238+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:54:28.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:28.287+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:54:28.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:54:28.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:28.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.159 seconds
[2024-05-01T14:54:58.899+0000] {processor.py:161} INFO - Started process (PID=1118) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:58.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:54:58.903+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:54:58.903+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:58.946+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:54:58.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:54:58.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:54:58.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.100 seconds
[2024-05-01T14:55:29.142+0000] {processor.py:161} INFO - Started process (PID=1129) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:29.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:55:29.146+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:55:29.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:29.193+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:55:29.185+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:55:29.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:29.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.095 seconds
[2024-05-01T14:55:59.516+0000] {processor.py:161} INFO - Started process (PID=1140) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:59.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:55:59.520+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:55:59.519+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:59.598+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:55:59.549+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:55:59.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:55:59.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.308 seconds
[2024-05-01T14:56:30.297+0000] {processor.py:161} INFO - Started process (PID=1152) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:56:30.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:56:30.300+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:56:30.300+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:56:30.382+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:56:30.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:56:30.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:56:30.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.144 seconds
[2024-05-01T14:57:01.478+0000] {processor.py:161} INFO - Started process (PID=1164) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:01.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:57:01.482+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:57:01.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:01.546+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:57:01.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:57:01.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:01.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.117 seconds
[2024-05-01T14:57:32.100+0000] {processor.py:161} INFO - Started process (PID=1175) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:32.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:57:32.135+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:57:32.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:32.181+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:57:32.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:57:32.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:57:32.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.145 seconds
[2024-05-01T14:58:02.320+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:02.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:58:02.324+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:58:02.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:02.379+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:58:02.370+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:58:02.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:02.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.098 seconds
[2024-05-01T14:58:33.458+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:33.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:58:33.461+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:58:33.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:33.497+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:58:33.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:58:33.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:58:33.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.088 seconds
[2024-05-01T14:59:03.810+0000] {processor.py:161} INFO - Started process (PID=1209) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:03.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:59:03.813+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:59:03.813+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:03.842+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:59:03.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:59:03.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:03.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.065 seconds
[2024-05-01T14:59:34.550+0000] {processor.py:161} INFO - Started process (PID=1219) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:34.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T14:59:34.553+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:59:34.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:34.590+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:59:34.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T14:59:34.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T14:59:34.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.072 seconds
[2024-05-01T15:00:04.826+0000] {processor.py:161} INFO - Started process (PID=1231) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:04.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:00:04.831+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:00:04.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:04.886+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:00:04.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:00:04.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:04.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.111 seconds
[2024-05-01T15:00:35.096+0000] {processor.py:161} INFO - Started process (PID=1242) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:35.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:00:35.101+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:00:35.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:35.141+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:00:35.135+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:00:35.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:00:35.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.137 seconds
[2024-05-01T15:01:05.523+0000] {processor.py:161} INFO - Started process (PID=1253) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:05.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:01:05.527+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:01:05.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:05.571+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:01:05.563+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:01:05.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:05.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.086 seconds
[2024-05-01T15:01:35.968+0000] {processor.py:161} INFO - Started process (PID=1264) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:35.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:01:35.973+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:01:35.972+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:36.026+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:01:36.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:01:36.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:01:36.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.108 seconds
[2024-05-01T15:02:06.203+0000] {processor.py:161} INFO - Started process (PID=1274) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:06.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:02:06.207+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:02:06.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:06.249+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:02:06.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:02:06.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:06.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.081 seconds
[2024-05-01T15:02:36.741+0000] {processor.py:161} INFO - Started process (PID=1285) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:36.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:02:36.746+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:02:36.745+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:36.787+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:02:36.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:02:36.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:02:36.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.078 seconds
[2024-05-01T15:03:07.483+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:07.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:03:07.486+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:03:07.485+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:07.523+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:03:07.515+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:03:07.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:07.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.073 seconds
[2024-05-01T15:03:38.078+0000] {processor.py:161} INFO - Started process (PID=1308) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:38.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:03:38.082+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:03:38.081+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:38.139+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:03:38.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:03:38.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:03:38.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.139 seconds
[2024-05-01T15:04:08.768+0000] {processor.py:161} INFO - Started process (PID=1319) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:08.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:04:08.774+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:04:08.773+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:08.815+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:04:08.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:04:08.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:08.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.082 seconds
[2024-05-01T15:04:39.278+0000] {processor.py:161} INFO - Started process (PID=1334) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:39.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:04:39.310+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:04:39.307+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:39.412+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:04:39.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:04:39.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:04:39.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.286 seconds
[2024-05-01T15:05:09.863+0000] {processor.py:161} INFO - Started process (PID=1345) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:09.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:05:09.867+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:05:09.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:09.912+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:05:09.904+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:05:09.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:09.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.091 seconds
[2024-05-01T15:05:40.065+0000] {processor.py:161} INFO - Started process (PID=1356) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:40.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:05:40.084+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:05:40.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:40.224+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:05:40.214+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:05:40.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:05:40.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.336 seconds
[2024-05-01T15:06:11.068+0000] {processor.py:161} INFO - Started process (PID=1367) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:11.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:06:11.072+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:06:11.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:11.107+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:06:11.101+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:06:11.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:11.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.073 seconds
[2024-05-01T15:06:41.428+0000] {processor.py:161} INFO - Started process (PID=1378) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:41.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:06:41.432+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:06:41.431+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:41.490+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:06:41.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:06:41.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:06:41.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.140 seconds
[2024-05-01T15:07:11.833+0000] {processor.py:161} INFO - Started process (PID=1388) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:11.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:07:11.836+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:07:11.836+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:11.895+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:07:11.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:07:11.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:11.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.114 seconds
[2024-05-01T15:07:42.423+0000] {processor.py:161} INFO - Started process (PID=1399) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:42.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:07:42.428+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:07:42.427+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:42.474+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:07:42.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:07:42.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:07:42.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.102 seconds
[2024-05-01T15:08:12.825+0000] {processor.py:161} INFO - Started process (PID=1410) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:12.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:08:12.831+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:08:12.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:12.874+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:08:12.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:08:12.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:12.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.104 seconds
[2024-05-01T15:08:43.012+0000] {processor.py:161} INFO - Started process (PID=1421) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:43.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:08:43.017+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:08:43.016+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:43.059+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:08:43.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:08:43.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:08:43.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.083 seconds
[2024-05-01T15:09:13.502+0000] {processor.py:161} INFO - Started process (PID=1432) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:13.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:09:13.508+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:09:13.506+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:13.557+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:09:13.549+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:09:13.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:13.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.094 seconds
[2024-05-01T15:09:43.839+0000] {processor.py:161} INFO - Started process (PID=1443) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:43.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:09:43.843+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:09:43.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:43.908+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:09:43.900+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:09:43.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:09:43.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.119 seconds
[2024-05-01T15:10:14.185+0000] {processor.py:161} INFO - Started process (PID=1454) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:14.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:10:14.188+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:10:14.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:14.226+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:10:14.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:10:14.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:14.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.077 seconds
[2024-05-01T15:10:44.442+0000] {processor.py:161} INFO - Started process (PID=1465) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:44.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:10:44.445+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:10:44.444+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:44.484+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:10:44.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:10:44.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:10:44.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.076 seconds
[2024-05-01T15:11:15.003+0000] {processor.py:161} INFO - Started process (PID=1477) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:15.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:11:15.006+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:11:15.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:15.041+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:11:15.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:11:15.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:15.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.073 seconds
[2024-05-01T15:11:45.205+0000] {processor.py:161} INFO - Started process (PID=1488) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:45.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:11:45.208+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:11:45.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:45.244+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:11:45.238+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:11:45.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:11:45.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.074 seconds
[2024-05-01T15:12:15.402+0000] {processor.py:161} INFO - Started process (PID=1499) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:15.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:12:15.407+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:12:15.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:15.453+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:12:15.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:12:15.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:15.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.095 seconds
[2024-05-01T15:12:45.884+0000] {processor.py:161} INFO - Started process (PID=1510) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:45.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:12:45.888+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:12:45.888+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:45.925+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:12:45.919+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:12:45.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:12:45.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.077 seconds
[2024-05-01T15:13:16.371+0000] {processor.py:161} INFO - Started process (PID=1522) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:16.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:13:16.375+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:13:16.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:16.428+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:13:16.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:13:16.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:16.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.136 seconds
[2024-05-01T15:13:47.020+0000] {processor.py:161} INFO - Started process (PID=1533) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:47.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:13:47.029+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:13:47.027+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:47.077+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:13:47.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:13:47.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:13:47.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.113 seconds
[2024-05-01T15:14:17.572+0000] {processor.py:161} INFO - Started process (PID=1545) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:17.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:14:17.580+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:14:17.579+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:17.619+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:14:17.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:14:17.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:17.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.095 seconds
[2024-05-01T15:14:47.723+0000] {processor.py:161} INFO - Started process (PID=1556) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:47.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:14:47.727+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:14:47.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:47.760+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:14:47.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:14:47.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:14:47.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.069 seconds
[2024-05-01T15:15:18.084+0000] {processor.py:161} INFO - Started process (PID=1567) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:18.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:15:18.087+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:15:18.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:18.116+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:15:18.112+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:15:18.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:18.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.067 seconds
[2024-05-01T15:15:49.775+0000] {processor.py:161} INFO - Started process (PID=1578) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:49.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:15:49.792+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:15:49.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:49.902+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:15:49.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:15:50.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:15:50.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.594 seconds
[2024-05-01T15:16:21.138+0000] {processor.py:161} INFO - Started process (PID=1589) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:21.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:16:21.145+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:16:21.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:21.206+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:16:21.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:16:21.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:21.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.123 seconds
[2024-05-01T15:16:51.873+0000] {processor.py:161} INFO - Started process (PID=1601) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:51.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:16:51.886+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:16:51.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:52.033+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:16:51.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:16:52.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:16:52.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.280 seconds
[2024-05-01T15:17:22.611+0000] {processor.py:161} INFO - Started process (PID=1612) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:22.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:17:22.616+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:17:22.615+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:22.678+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:17:22.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:17:22.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:22.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.115 seconds
[2024-05-01T15:17:52.946+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:52.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:17:52.950+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:17:52.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:52.993+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:17:52.986+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:17:52.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:17:53.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.116 seconds
[2024-05-01T15:18:23.944+0000] {processor.py:161} INFO - Started process (PID=1634) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:23.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:18:23.956+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:18:23.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:24.103+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:18:24.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:18:24.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:24.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.269 seconds
[2024-05-01T15:18:55.019+0000] {processor.py:161} INFO - Started process (PID=1645) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:55.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:18:55.033+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:18:55.032+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:55.182+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:18:55.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:18:55.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:18:55.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.296 seconds
[2024-05-01T15:19:25.648+0000] {processor.py:161} INFO - Started process (PID=1656) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:25.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:19:25.666+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:19:25.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:25.721+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:19:25.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:19:25.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:25.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.133 seconds
[2024-05-01T15:19:56.456+0000] {processor.py:161} INFO - Started process (PID=1668) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:56.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:19:56.466+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:19:56.465+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:56.585+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:19:56.566+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:19:56.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:19:56.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.240 seconds
[2024-05-01T15:20:27.115+0000] {processor.py:161} INFO - Started process (PID=1678) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:27.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:20:27.122+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:20:27.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:27.227+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:20:27.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:20:27.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:27.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.202 seconds
[2024-05-01T15:20:57.686+0000] {processor.py:161} INFO - Started process (PID=1689) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:57.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:20:57.690+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:20:57.689+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:57.731+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:20:57.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:20:57.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:20:57.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.087 seconds
[2024-05-01T15:21:27.987+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:27.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:21:27.999+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:21:27.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:28.125+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:21:28.118+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:21:28.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:28.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.201 seconds
[2024-05-01T15:21:58.762+0000] {processor.py:161} INFO - Started process (PID=1711) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:58.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:21:58.771+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:21:58.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:58.868+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:21:58.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:21:58.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:21:58.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.207 seconds
[2024-05-01T15:22:29.495+0000] {processor.py:161} INFO - Started process (PID=1722) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:22:29.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:22:29.498+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:22:29.498+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:22:29.539+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:22:29.533+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:22:29.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:22:29.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.091 seconds
[2024-05-01T15:23:00.151+0000] {processor.py:161} INFO - Started process (PID=1732) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:00.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:23:00.155+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:23:00.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:00.199+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:23:00.192+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:23:00.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:00.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.090 seconds
[2024-05-01T15:23:30.720+0000] {processor.py:161} INFO - Started process (PID=1743) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:30.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:23:30.723+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:23:30.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:30.763+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:23:30.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:23:30.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:23:30.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.083 seconds
[2024-05-01T15:24:01.392+0000] {processor.py:161} INFO - Started process (PID=1754) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:01.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:24:01.400+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:24:01.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:01.460+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:24:01.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:24:01.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:01.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.136 seconds
[2024-05-01T15:24:32.170+0000] {processor.py:161} INFO - Started process (PID=1771) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:32.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:24:32.175+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:24:32.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:32.219+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:24:32.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:24:32.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:24:32.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.097 seconds
[2024-05-01T15:25:02.528+0000] {processor.py:161} INFO - Started process (PID=1782) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:02.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:25:02.535+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:25:02.534+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:02.590+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:25:02.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:25:02.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:02.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.117 seconds
[2024-05-01T15:25:33.043+0000] {processor.py:161} INFO - Started process (PID=1793) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:33.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:25:33.049+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:25:33.048+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:33.099+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:25:33.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:25:33.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:25:33.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.108 seconds
[2024-05-01T15:26:03.858+0000] {processor.py:161} INFO - Started process (PID=1804) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:03.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:26:03.885+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:26:03.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:04.041+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:26:04.008+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:26:04.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:04.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.353 seconds
[2024-05-01T15:26:34.275+0000] {processor.py:161} INFO - Started process (PID=1815) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:34.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:26:34.280+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:26:34.279+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:34.357+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:26:34.348+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:26:34.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:26:34.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.153 seconds
[2024-05-01T15:27:04.620+0000] {processor.py:161} INFO - Started process (PID=1826) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:04.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:27:04.649+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:27:04.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:04.758+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:27:04.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:27:04.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:04.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.217 seconds
[2024-05-01T15:27:35.973+0000] {processor.py:161} INFO - Started process (PID=1838) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:35.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:27:35.986+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:27:35.984+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:36.142+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:27:36.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:27:36.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:27:36.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.292 seconds
[2024-05-01T15:28:07.931+0000] {processor.py:161} INFO - Started process (PID=1850) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:07.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:28:07.941+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:28:07.939+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:08.009+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:28:08.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:28:08.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:08.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.156 seconds
[2024-05-01T15:28:38.726+0000] {processor.py:161} INFO - Started process (PID=1862) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:38.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:28:38.733+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:28:38.732+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:38.779+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:28:38.774+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:28:38.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:28:38.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.097 seconds
[2024-05-01T15:29:09.639+0000] {processor.py:161} INFO - Started process (PID=1873) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:09.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:29:09.644+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:29:09.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:09.688+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:29:09.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:29:09.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:09.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.100 seconds
[2024-05-01T15:29:40.127+0000] {processor.py:161} INFO - Started process (PID=1883) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:40.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:29:40.136+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:29:40.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:40.692+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:29:40.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:29:40.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:29:40.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.739 seconds
[2024-05-01T15:30:11.115+0000] {processor.py:161} INFO - Started process (PID=1894) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:11.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:30:11.118+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:30:11.118+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:11.152+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:30:11.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:30:11.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:11.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.076 seconds
[2024-05-01T15:30:41.796+0000] {processor.py:161} INFO - Started process (PID=1905) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:41.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:30:41.800+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:30:41.800+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:41.846+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:30:41.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:30:41.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:30:41.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.091 seconds
[2024-05-01T15:31:12.523+0000] {processor.py:161} INFO - Started process (PID=1916) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:12.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:31:12.527+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:31:12.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:12.564+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:31:12.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:31:12.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:12.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.082 seconds
[2024-05-01T15:31:45.681+0000] {processor.py:161} INFO - Started process (PID=1928) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:45.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:31:46.098+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:31:46.096+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:46.274+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:31:46.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:31:46.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:31:46.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.721 seconds
[2024-05-01T15:32:16.549+0000] {processor.py:161} INFO - Started process (PID=1939) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:16.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:32:16.554+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:32:16.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:16.689+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:32:16.667+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:32:16.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:16.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.196 seconds
[2024-05-01T15:32:47.079+0000] {processor.py:161} INFO - Started process (PID=1949) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:47.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:32:47.083+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:32:47.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:47.127+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:32:47.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:32:47.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:32:47.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.092 seconds
[2024-05-01T15:33:18.456+0000] {processor.py:161} INFO - Started process (PID=1961) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:18.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:33:18.467+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:33:18.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:18.615+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:33:18.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:33:18.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:18.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.252 seconds
[2024-05-01T15:33:49.394+0000] {processor.py:161} INFO - Started process (PID=1972) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:49.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:33:49.399+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:33:49.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:49.454+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:33:49.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:33:49.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:33:49.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.118 seconds
[2024-05-01T15:34:20.189+0000] {processor.py:161} INFO - Started process (PID=1984) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:20.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:34:20.193+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:34:20.192+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:20.241+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:34:20.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:34:20.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:20.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.110 seconds
[2024-05-01T15:34:50.890+0000] {processor.py:161} INFO - Started process (PID=1995) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:50.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:34:50.898+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:34:50.897+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:51.008+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:34:50.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:34:51.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:34:51.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.191 seconds
[2024-05-01T15:35:21.596+0000] {processor.py:161} INFO - Started process (PID=2006) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:21.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:35:21.600+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:35:21.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:21.646+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:35:21.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:35:21.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:21.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.093 seconds
[2024-05-01T15:35:52.097+0000] {processor.py:161} INFO - Started process (PID=2017) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:52.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:35:52.102+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:35:52.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:52.142+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:35:52.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:35:52.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:35:52.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.085 seconds
[2024-05-01T15:36:22.550+0000] {processor.py:161} INFO - Started process (PID=2028) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:22.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:36:22.555+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:36:22.554+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:22.610+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:36:22.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:36:22.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:22.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.146 seconds
[2024-05-01T15:36:53.069+0000] {processor.py:161} INFO - Started process (PID=2039) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:53.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:36:53.075+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:36:53.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:53.132+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:36:53.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:36:53.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:36:53.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.113 seconds
[2024-05-01T15:37:24.082+0000] {processor.py:161} INFO - Started process (PID=2050) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:24.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:37:24.085+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:37:24.085+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:24.126+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:37:24.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:37:24.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:24.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.090 seconds
[2024-05-01T15:37:54.693+0000] {processor.py:161} INFO - Started process (PID=2063) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:54.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:37:54.699+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:37:54.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:54.746+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:37:54.738+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:37:54.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:37:54.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.101 seconds
[2024-05-01T15:38:24.891+0000] {processor.py:161} INFO - Started process (PID=2074) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:24.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:38:24.895+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:38:24.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:24.932+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:38:24.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:38:24.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:24.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.077 seconds
[2024-05-01T15:38:55.434+0000] {processor.py:161} INFO - Started process (PID=2085) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:55.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:38:55.446+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:38:55.444+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:55.587+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:38:55.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:38:55.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:38:55.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.278 seconds
[2024-05-01T15:39:26.257+0000] {processor.py:161} INFO - Started process (PID=2096) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:26.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:39:26.263+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:39:26.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:26.320+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:39:26.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:39:26.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:26.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.125 seconds
[2024-05-01T15:39:56.661+0000] {processor.py:161} INFO - Started process (PID=2107) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:56.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:39:56.666+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:39:56.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:56.727+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:39:56.718+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:39:56.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:39:56.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.162 seconds
[2024-05-01T15:40:26.984+0000] {processor.py:161} INFO - Started process (PID=2118) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:26.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:40:26.989+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:40:26.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:27.131+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:40:27.119+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:40:27.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:27.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.234 seconds
[2024-05-01T15:40:58.247+0000] {processor.py:161} INFO - Started process (PID=2129) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:58.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:40:58.252+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:40:58.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:58.307+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:40:58.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:40:58.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:40:58.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.114 seconds
[2024-05-01T15:41:28.592+0000] {processor.py:161} INFO - Started process (PID=2140) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:28.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:41:28.598+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:41:28.598+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:28.658+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:41:28.651+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:41:28.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:28.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.116 seconds
[2024-05-01T15:41:59.287+0000] {processor.py:161} INFO - Started process (PID=2152) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:59.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:41:59.291+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:41:59.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:59.332+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:41:59.326+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:41:59.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:41:59.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.112 seconds
[2024-05-01T15:42:29.584+0000] {processor.py:161} INFO - Started process (PID=2163) to work on /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:42:29.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kolesa/kolesa.py for tasks to queue
[2024-05-01T15:42:29.590+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:42:29.589+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:42:29.675+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:42:29.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kolesa/kolesa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kolesa/kolesa.py", line 6, in <module>
    from kolesa_utils import *
ModuleNotFoundError: No module named 'kolesa_utils'
[2024-05-01T15:42:29.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kolesa/kolesa.py
[2024-05-01T15:42:29.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kolesa/kolesa.py took 0.184 seconds
