[2024-04-21T11:03:21.737+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-03-04T00:00:00+00:00 [queued]>
[2024-04-21T11:03:21.946+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-03-04T00:00:00+00:00 [queued]>
[2024-04-21T11:03:21.967+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T11:03:22.275+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_rub> on 2024-03-04 00:00:00+00:00
[2024-04-21T11:03:22.349+0000] {standard_task_runner.py:60} INFO - Started process 2363 to run task
[2024-04-21T11:03:22.416+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_rub', 'scheduled__2024-03-04T00:00:00+00:00', '--job-id', '1904', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmp20qdd3z3']
[2024-04-21T11:03:22.466+0000] {standard_task_runner.py:88} INFO - Job 1904: Subtask get_data_rub
[2024-04-21T11:03:23.528+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_rub scheduled__2024-03-04T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T11:03:24.200+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T11:03:24.823+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_rub' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-04T00:00:00+00:00'
[2024-04-21T11:03:36.198+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 37, in get_data_rub
    currencies_date = datetime.strptime(currency_data['Date'][:10], '%Y-%m-%d')
KeyError: 'Date'
[2024-04-21T11:03:36.235+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=get_data_rub, execution_date=20240304T000000, start_date=20240421T110321, end_date=20240421T110336
[2024-04-21T11:03:36.569+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1904 for task get_data_rub ('Date'; 2363)
[2024-04-21T11:03:36.735+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T11:03:37.042+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
